### PR TITLE
Add contract to check class AND sub-class

### PR DESCRIPTION
**Pull request by dg-ratiodata**
This PR adds a contract which checks the class and the sub-class of a given object.

### CODE REVIEW

**Comment by alex-fedorov** [comment]
This is not really needed, because this works already:

```ruby
class A; end
class B < A; end

Contract A => nil
def something(x) end

something(A.new)    # => nil
something(B.new)    # => nil
something(Object.new)   # raise ContractError
```

**Comment by alex-fedorov** [comment]
It is implemented in validators: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts/validators.rb#L44-L46

**Comment by dg-ratiodata** [comment]
Cool. Didn't know that. Is there any documentation I oversaw?

**Comment by waterlink** [comment]
Probably not. It is just how type restriction in typed languages naturally
work.

We might want to add this to documentation, but the problem is that we have
only tutorial, that is already quite bloated. We might as well want to
split it in two. WDYT @egonSchiele?

**Comment by dg-ratiodata** [comment]
Why not using `cucumber`+ `aruba` for this? Although I'm a bit biased. :smile:

The guys at rspec use cucumber to describe how to use their software. `aruba`
is used behind the scenes. Might be worth to checkout for you as well. We at `aruba` like that idea and started to migrate our very own features to such a theme. They look something like that.

```cucumber
Feature: Checking Class Type
  Scenario: Object is of Class
    Given a file named "lib/my_lib/my_class.rb" with
    """
    require 'contracts'

    module MyLib
      class MyClass
        include Contracts

        Contract Numeric => nil
        def do_some_work(arg)
        end
      end
    end
    """
    And a file named "spec/class_type_spec.rb" with:
    """
    require 'spec_helper'
    require_relative 'my_lib/my_class' # just to demonstrate, normally I would move that thing into the spec helper

    RSpec.describe "Class Type Checking" do
      subject { MyClass.new }

      context 'when is valid' do
        let(:arg) { 1 }
        it do
          expect do
            subject.do_some_work
          end.not_to raise_error
        end
      end

      context 'when is invalid' do
        let(:arg) { 'asdf' }
        it do
          expect do
            subject.do_some_work
          end.to raise_error ArgumentError
        end
      end
    end
    """
    When I run `rspec`
    Then the specs should all pass
```

The good thing is, you've got tests you can run, but also a pretty good documentation your users can use. Maybe you could even upload that stuff to ["relish"](https://www.relishapp.com/) if you like.

**Comment by alex-fedorov** [comment]
@dg-ratiodata Just check out this: https://github.com/egonSchiele/contracts.ruby/tree/0.99-before-release :D

**Comment by alex-fedorov** [comment]
This is old non-updated branch, but soon we will take care of it in preparation of `1.0.0` and it already has cucumber/aruba scenarios in it :)

**Comment by dg-ratiodata** [comment]
Great!

**Comment by egonSchiele** [comment]
Yes, I was just thinking about that this week. I can split out the tutorial.

**Pull request closed without merging**
