### PR TITLE
Update changelog for 0.10

### PR DESCRIPTION
**Pull request by waterlink**
So this is the list of important changes between `0.9` and `0.10`. My wording is probably not the best, so please review :)

/cc @egonSchiele @PikachuEXE

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I think it is good enough, though having links to PRs would be even better :)

**Comment by alex-fedorov** [comment]
@PikachuEXE Done

**Comment by PikachuEXE** [comment]
Nice! :+1:

**Comment by egonSchiele** [comment]
Awesome! Links are really nice :)

**Pull request merged**
