### PR TITLE
RangeOf[...] implemented

### PR DESCRIPTION
**Pull request by gsinclair**
E.g. RangeOf[Nat] or RangeOf[String] or ...

Includes tests but not TUTORIAL.md as that is under potential change
from pull request #170.

[Feature request #169]

### CODE REVIEW

**Comment by alex-fedorov** [comment]
Can you use && instead of and?

I don't see a reason to not add this to tutorial in this PR.

Otherwise looks good.

**Comment by gsinclair** [comment]
Both done in commit baed1fd.

**Comment by gsinclair** [comment]
Hmm... I tested on one machine and had no problem. (I forget the ruby version of that machine and can't access it right now.) But now on another machine I've got errors. Another commit needed.

As a matter of interest, one of these is bad code:

```ruby
3.is_a? Integer and 6 > 3
3.is_a? Integer && 6 > 3
```

**Comment by waterlink** [comment]
Yeah, that is why `&&` is preferred in ruby community: `and` has unexpected operator priority.

**Comment by waterlink** [comment]
Rubocop reports some issues on travis, can you fix them ?

**Comment by gsinclair** [comment]
Done using local rubocop.

**Pull request merged**
