### PR TITLE
Travis: Create a separate RuboCop "Build Stage"

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR makes RuboCop run in a Travis _Build Stage_ before the testing begins.

- This allows the test `script` to be `bundle exec rspec && bundle exec cucumber`.
- JRuby 1.7.27 gets to run only `bundle exec rspec` (it doesn't support the Cucumber suite)
- Drop RuboCop Rake task
- Drop Cucumber wrapper script
- Add latest available Ruby versions to CI matrix

See [Travis' docs for examples of Build Stage matrix expansion usage](https://docs.travis-ci.com/user/build-stages/matrix-expansion/).

This change enables us to upgrade to the very latest RuboCop, which is supported on Ruby 2+. (Beyond the scope of this PR.)

### CODE REVIEW

**Comment by olleolleolle** [comment]
There's probably a couple more splits that could be done; Build Stages have not yielded all its useful secrets yet!

**Comment by olleolleolle** [comment]
Hrm, I need to execute a string as a shell command. I'll get to the bottom of this!

**Comment by olleolleolle** [comment]
With the help of a trusted friend, I smote the dragon of complexity, cutting the size of the configuration and also of the CI matrix!

**Comment by egonSchiele** [comment]
Thanks for filing all these PRs! Awesome to have these contributions! 👍

**Pull request merged**
