### PR TITLE
Bug/44: Fix contracts on modules

### LINKED ISSUE #44: contracts on modules don't get checked
See [this issue](https://github.com/snowplow/snowplow/issues/906). Replicate with [this code](https://gist.github.com/egonSchiele/c7d0f44d1e3b2407743e). If you change `module Cli` to `class Cli`, it works.

### PR DESCRIPTION
**Pull request by waterlink**
fixes #44

### CODE REVIEW

**Comment by waterlink** [comment]
And of course build failed on some rubies, I will look into it later.

**Comment by waterlink** [comment]
Now, it looks a bit better. @egonSchiele can you review this one?

**Comment by waterlink** [comment]
updated to be merge-able

**Comment by egonSchiele** [comment]
Awesome!

**Pull request merged**
