### PR TITLE
Add a couple CHANGELOG entries.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
egonSchiele, if it's possible, any chance you could cut a release if this merges? Would be great to use the new `Attrs` module in some projects I work on. No rush at all though if you're busy :)

**Comment by egonSchiele** [comment]
Yup! I'll do this now.

**Comment by egonSchiele** [comment]
Ok, rubygems seems to be down for me. I'll try again in a bit, in the meantime I've version bumped contracts on github.

**Comment by frewsxcv** [comment]
Oh weird! What kind of error do you get when you attempt to publish?

**Comment by egonSchiele** [comment]
```
contracts.ruby (master) $ gem push contracts-0.16.0.gem
ERROR:  While executing gem ... (RuntimeError)
    Can't find 'rubygems-update' in any repo. Check `gem source list`.
contracts.ruby (master) $ gem source list
*** CURRENT SOURCES ***

https://rubygems.org/
contracts.ruby (master) $
```

**Comment by frewsxcv** [comment]
What version of gem do you have?

Also, this is _completely_ up to you and you shouldn't feel pressured to do so, but if you're willing to (even temporarily) give out rubygems permissions, I'd be happy to push it up for you

**Comment by egonSchiele** [comment]
Ok, pushed! Didn't work with this version:

```
contracts.ruby (master) $ gem --version
2.4.6
contracts.ruby (master) $ which gem
/Users/abhargava/.rvm/rubies/ruby-2.2.1/bin/gem
```

Did work with:

```
contracts.ruby (master) $ gem -v
2.5.1
contracts.ruby (master) $ which gem
/usr/local/rvm/rubies/ruby-2.3.0/bin/gem
```

So weird.

**Comment by frewsxcv** [comment]
Awesome, glad to hear it worked :)

Thanks again for everything!

**Pull request merged**
