### PR TITLE
Add note on 'include Contracts::Builtin' to tutorial

### LINKED ISSUE #200: Add info on `include Contracts::Builtin` to tutorial

### PR DESCRIPTION
**Pull request by waterlink**
Does exactly what the title says ;)

/cc @egonSchiele @PikachuEXE 

fixes #200

### CODE REVIEW

**Comment by PikachuEXE** [comment]
So which way is more "recommended" now?
```ruby
include Contracts
```
or
```ruby
include Contracts::Core
include Contracts::Builtin
```
I am asking this since the section `Built-in Contracts` is saying:
`The easiest way to use them is to include the Contracts module in your class/module.`

**Comment by waterlink** [comment]
`Core` + `Builtin`

**Comment by waterlink** [comment]
@PikachuEXE thanks for noticing `the easiest way to use them ...`. This needs to be fixed to point to `Contracts::Builtin`

**Comment by waterlink** [comment]
Updated aforementioned sentence, to reflect current reality.

**Comment by PikachuEXE** [comment]
The "Hello World" section in `README.md` also needs to be changed?

**Comment by waterlink** [comment]
I don't see hello world section in readme.. Do you mean this: https://github.com/waterlink/contracts.ruby/blob/include-builtin-tutorial/TUTORIAL.md#hello-world ?

**Comment by PikachuEXE** [comment]
https://github.com/egonSchiele/contracts.ruby#hello-world
```
require 'contracts'
include Contracts

Contract Num => Num
def double(x)
  x * 2
end

puts double("oops")
```

**Comment by waterlink** [comment]
Okay, I see it now :D (I was looking for typical hello world code..) Yeah,
you are right.

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-17 0:45 GMT+02:00 PikachuEXE <notifications@github.com>:

**Comment by waterlink** [comment]
Done

**Comment by PikachuEXE** [comment]
I can't find any more place with deprecated reference
LGTM

`gh-pages` needs to be changed as well? (I know it will be another PR)

**Comment by waterlink** [comment]
gh-pages are autogenerated when release happens. Am I right @egonSchiele?

**Comment by egonSchiele** [comment]
Yes, gh-pages is generated by github. I'll kick off the generation now.

**Pull request merged**
