### PR TITLE
Fix warning for pattern match

### PR DESCRIPTION
**Pull request by dg-ratiodata**
+ Easier testing for outsiders....

### CODE REVIEW

**Comment by alex-fedorov** [comment]
@dg-ratiodata I figured it out, why `ruby_22` is not available: #180

**Comment by alex-fedorov** [comment]
@dg-ratiodata try to rebase, should work now

**Comment by dg-ratiodata** [comment]
Re-push to trigger rebuild

**Comment by dg-ratiodata** [comment]
Finished. All green.

**Comment by alex-fedorov** [comment]
I have a feeling, that re-pushing is not enough. You need to rebase against upstream master. This might help: https://gist.github.com/waterlink/ee7600e499d2ca8c596f

**Comment by alex-fedorov** [comment]
Hmm, I don't quite understand how you did it green..

**Comment by dg-ratiodata** [comment]
Magic... No, just `git commit --amend && git push -f` Then travis sees a new commit and starts again.

**Comment by alex-fedorov** [comment]
I see. Our travis setup uses pr/XXX/merge instead of pr/XXX/head. And I think it should use both.

**Comment by alex-fedorov** [comment]
Ok, I will rebase manually and merge it. I don't want to make merge diversions in the tree.

**Comment by dg-ratiodata** [comment]
ok. Thanks.

**Comment by alex-fedorov** [comment]
Merged manually

**Pull request closed without merging**
