### PR TITLE
Allow contracts on singleton class of subclass

### PR DESCRIPTION
**Pull request by waterlink**
fixes #210

### CODE REVIEW

**Comment by waterlink** [comment]
Oh that is so meta. I have run into problems with our feature (cucumber) specs for `contracts.ruby` because I have broken functionality that `cucumber/aruba` uses from `contracts.ruby`.

**Comment by waterlink** [comment]
Finally made this pass on all rubies.

@betamatt @egonSchiele Can you take a look?

**Comment by egonSchiele** [comment]
Looks great to me, thanks @waterlink ! Lets see if @betamatt has any comments, otherwise I will merge this.

**Comment by betamatt** [comment]
Thanks a lot.

I haven't studied enough on how you've got this wired so I can't judge the implementation. However, I'll see if I can find some time today to try it out on our codebase and verify that there aren't any obvious regressions.

**Comment by egonSchiele** [comment]
In that case I have just merged it. Thanks @betamatt and @waterlink !

**Pull request merged**
