### PR TITLE
fixes #154: Don't include contracts internals into users classes

### PR DESCRIPTION
**Pull request by waterlink**
Looks like a good fix for #154. Thanks to @nixpulvis for the idea on `.append_features` hook.

Lets see if travis passes.

/cc @guizmaii : can you try this branch if it works for your application?

/ccc @egonSchiele @nixpulvis : WDYT on this solution?

### CODE REVIEW

**Comment by waterlink** [comment]
BTW, since I wrapped all builtin contracts in their own namespace, you better read the PR with `?w=1` to hide all whitespace-only changes and see only relevant ones. I.e.: [just-use-this-link](https://github.com/egonSchiele/contracts.ruby/pull/155/files?w=1)

**Comment by nixpulvis** [comment]
The approach looks good to me. I cannot attest to everyone that needs to be fixed because of it working.

**Comment by guizmaii** [comment]
It doesn't seem to work. 

It seems to fix the ```Support``` name collision problem but other problems appear.

I have a ```Client``` model in my Rails app that has many ```Store```. With this patch, when I do something like that : ```client.stores``` it throw an exception : ```Client::Store constant does not exist```

Strange !

**Comment by waterlink** [comment]
Can you pin it down to small example? Does this error go away if you rename
Client to something else? Does this error go away if you stop using grape
gem?

**Comment by guizmaii** [comment]
I'll do some tests maybe tomorrow or next week. For now I don't have a lot of time.

**Comment by nixpulvis** [comment]
For referance this is related to the larger issue of namespace collisions we should be weary of. Related to #157.

**Comment by alex-fedorov** [comment]
@guizmaii Any news on this one? Have you been able to play around with it?

**Comment by egonSchiele** [comment]
works for me!

**Comment by alex-fedorov** [comment]
Hmm, I wonder. What happens in this case:

```ruby
module A
  include Contracts

  class B
  end
end

class X
  include A

  def b_class
    B
  end
end
```

**Comment by waterlink** [comment]
I'm closing this for now, because #157 discussion may result in way better solution.

**Pull request closed without merging**
